# Generated by Django 5.0.6 on 2024-05-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
