# Generated by Django 5.0.6 on 2024-05-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
