# Generated by Django 5.0.6 on 2024-05-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_alter_tarea_fecha_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
