# Generated by Django 5.0.6 on 2024-05-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='es_video_album',
            field=models.BooleanField(default=False),
        ),
    ]
